config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'auth/registrations'
  }
  namespace :external_coach do
    root "users#index"
    get "login" => "sessions#new", as: :login
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy"


    # profileルーティング
    resource :profile

    # userルーティング
    resources :users

    # 記事
    resources :articles

    # accountルーティング
    resource :account, only: [:show, :edit, :update]

    # passwordルーティング
    resource :password, only: [:show, :edit, :update]
  end

  namespace :club_advisor do
    get "login" => "sessions#new", as: :login
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy"

    root "articles#index"

    # 記事
    resources :external_coaches 
    resources :articles

    # accountルーティング
    resource :account, only: [:show, :edit, :update]

    # userルーティング
    resources :users
    
    # profileルーティング
    resource :profile

    # passwordルーティング
    resource :password, only: [:show, :edit, :update]
  end
end

app/models/external_coach.rb
class ExternalCoach < ApplicationRecord
  has_one :ec_article, dependent: :destroy 

  # 外部コーチがフォローしているクラブアドバイザーの関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :follower

  # 外部コーチをフォローしているクラブアドバイザーの関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

  # current_passwordの書き込み・読み取りを可能にする
  attr_accessor :current_password

  # バリデーションの設定
  HUMAN_NAME_REGEXP = /\A[\p{han}\p{hiragana}\p{katakana}\u{30fc}A-Za-z]+\z/
  KATAKANA_REGEXP = /\A[\p{katakana}\u{30fc}]+\z/

  validates :email, presence: true, "valid_email_2/email": true,
    uniqueness: { case_sensitive: false }
  validates :family_name, :given_name, presence: true,
    format: { with: HUMAN_NAME_REGEXP, allow_blank: true }
  validates :family_name_kana, :given_name_kana, presence: true,
    format: { with: KATAKANA_REGEXP, allow_blank: true }
  validates :start_date, presence: true, date: {
    after_or_equal_to: Date.new(2000, 1, 1),
    before: -> (obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
  validates :end_date, date: {
    after: :start_date,
    before: -> (obj) { 1.year.from_now.to_date },
    allow_blank: true
  }

  # パスワード変更時のバリデーション, このバリデーションは、「password」という属性（カラム）に対して、存在性（presence）のバリデーションを行うことを意味しています。「if: :current_password」というオプションは、「current_password」というメソッドが「true」を返す場合のみバリデーションが実行されます。
  validates :password, presence: {if: :current_password}

  validate :above_18_years_old

  def above_18_years_old
    if birthday.present? && birthday >= 18.years.ago.to_date
      errors.add(:birthday, "must be above 18 years old")
    end
  end

  validates :sex, presence: true

  def is_followed_by?(club_advisor)
    active_relationships.find_by(follower_id: club_advisor.id).present?
  end
end

app/controllers/club_advisor/accounts_controller.rb
class ClubAdvisor::AccountsController < ClubAdvisor::Base
  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @club_advisor = current_club_advisor
  end

  def edit
    @club_advisor = current_club_advisor
  end
  
  def update
    @club_advisor = current_club_advisor
    @club_advisor.assign_attributes(ca_account_params)
    if @club_advisor.save
      redirect_to :club_advisor_account, notice: "アカウント情報を更新しました。"
    else
      render "edit"
    end
  end

  private def ca_account_params
    params.require(:club_advisor).permit(
        :email,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :school_id,
        :club_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end

end

app/controllers/external_coach/accounts_controller.rb
class ExternalCoach::AccountsController < ExternalCoach::Base

  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @external_coach = current_external_coach
  end

  def edit
    @external_coach = current_external_coach
  end
  
  def update
    @external_coach = current_external_coach
    @external_coach.assign_attributes(ec_account_params)
    if @external_coach.save
      redirect_to :external_coach_account, notice: "アカウント情報を更新しました。"
    else
      render "edit"
    end
  end

  private def ec_account_params
    params.require(:external_coach).permit(
        :email,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end
end

app/controllers/external_coach/articles_controller.rb
class ExternalCoach::ArticlesController < ExternalCoach::Base
  
  #クラブアドバイザー:記事一覧
  def index
      @articles = CaArticle.common
      .visible.order(released_at: :desc)
      .page(params[:page]).per(5)
      render json: @articles
  end

  # クラブアドバイザー:記事詳細
  def show
    @article = CaArticle.find(params[:id])
  end
end

app/controllers/external_coach/base.rb
class ExternalCoach::Base < ApplicationController
  private def current_external_coach
    if session[:external_coach_id]
      @current_external_coach ||=
        ExternalCoach.find_by(id: session[:external_coach_id])
    end
  end
  
  # before_actionコールバックとして使うためlogin_requiredを作成
  private def login_required
    raise LoginRequired unless current_external_coach
  end
  helper_method :current_external_coach
end

app/controllers/external_coach/passwords_controller.rb
class ExternalCoach::PasswordsController < ExternalCoach::Base
  before_action :login_required

  def show
    redirect_to :edit_external_coach_password
  end

  def edit
    @change_password_form =
      ExternalCoach::ChangePasswordForm.new(object: current_external_coach)
  end

  def update
    @change_password_form = ExternalCoach::ChangePasswordForm.new(external_coach_params)
    @change_password_form.object = current_external_coach
    if @change_password_form.save
      flash.notice = "パスワードを変更しました。"
      redirect_to :external_coach_account
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "edit"
    end
  end

  private def external_coach_params
    params.require(:external_coach_change_password_form).permit(
      :current_password, :new_password, :new_password_confirmation
    )
  end

end

app/controllers/external_coach/profiles_controller.rb
class ExternalCoach::ProfilesController < ExternalCoach::Base
  
  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
  end

  # 外部コーチ:編集フォーム
  def edit
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
  end

  # 外部コーチ:新規登録フォーム
  def new
    if EcArticle.exists?(external_coach_id: current_external_coach)
      redirect_to :external_coach_articles
    else
      @article = EcArticle.new
    end
  end

  # 外部コーチ:新規作成
  def create
    @article = EcArticle.new(ec_article_params)
    @article.author = current_external_coach
    if @article.save
      redirect_to :external_coach_profile, notice: "ニュース記事を登録しました。"
    else
      render "new"
    end
  end

  # 外部コーチ:更新
  def update
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
    @article.assign_attributes(ec_article_params)
    if @article.save
      redirect_to external_coach_profile_path(@article), notice: "ニュース記事を更新しました。"
    else
      render "edit"
    end
  end

  # 外部コーチ:削除
  def destroy
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
    @article.destroy
    redirect_to :external_coach_profile
  end

  private def ec_article_params
    params.require(:ec_article).permit(
        :title,
        :body_1,
        :body_2,
        :body_3,
        :released_at,
        :expired_at,
        :no_expiration,
        :external_coach_only,
        :external_coach_id,
        :status
    )
  end
  
  private def redirect_if_data_present
    if current_external_coach.ec_article.present?
        redirect_to :external_coach_articles
    end
  end
end

app/controllers/external_coach/relationships_controller.rb
class ExternalCoach::RelationshipsController < ExternalCoach::Base
  before_action :login_required
  def create
    following = current_external_coach.active_relationships.build(follower_id: params[:club_advisor_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_external_coach.active_relationships.find_by(follower_id: params[:club_advisor_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/controllers/external_coach/sessions_controller.rb
class ExternalCoach::SessionsController < ExternalCoach::Base
  def new
    if current_external_coach
      redirect_to :external_coach_root
    else
      @form = ExternalCoach::LoginForm.new
      render action: "new"
    end
  end

  def create
    @form = ExternalCoach::LoginForm.new(login_form_params)
    if @form.email.present?
      external_coach =
        ExternalCoach.find_by("LOWER(email) = ?", @form.email.downcase)
    end
    if ExternalCoach::Authenticator.new(external_coach).authenticate(@form.password)
      if external_coach.suspended?
        flash.now.alert = "アカウントが停止されています。"
        render action: "new"
      else
        session[:external_coach_id] = external_coach.id
        flash.notice = "ログインしました。"
        redirect_to :external_coach_users
      end
    else
      flash.now.alert = "メールアドレスまたはパスワードが正しくありません。"
      render action: "new"
    end
  end

  private def login_form_params
    params.require(:external_coach_login_form).permit(:email, :password)
  end

  def destroy
    session.delete(:external_coach_id)
    flash.notice = "ログアウトしました。"
    redirect_to :external_coach_root
  end
end

app/controllers/external_coach/users_controller.rb
class ExternalCoach::UsersController < ExternalCoach::Base
  def index
    @external_coach = ExternalCoach.order(:family_name_kana, :given_name_kana)
    # ページネーション
    .page(params[:page]).per(15)
    render json: @external_coach
  end

  def show
    @external_coach = ExternalCoach.find(params[:id])
    redirect_to [ :edit, :admin, external_coach ]
  end

  def new
    if current_external_coach
      redirect_to :external_coach_root
    else
      @external_coach = ExternalCoach.new
      render action: "new"
    end
  end

  def edit
    @external_coach = ExternalCoach.find(params[:id])
  end

  def update
    @external_coach = ExternalCoach.find(params[:id])
    @external_coach.assign_attributes(params[:external_coach])
    if @external_coach.save
      flash.notice = "職員アカウントを更新しました。"
      redirect_to :external_coach_users
    else
      render action: "edit"
    end
  end
 
  def create
    @external_coach = ExternalCoach.new(external_coach_params)
    if @external_coach.save
      flash.notice = "職員アカウントを新規登録しました。"
      #redirect_to :external_coach_root

      @form = ExternalCoach::LoginForm.new(new_form_params)
      if @form.email.present?
        external_coach =
          ExternalCoach.find_by("LOWER(email) = ?", @form.email.downcase)
      end
        if ExternalCoach::Authenticator.new(external_coach).authenticate(@form.password)
          session[:external_coach_id] = external_coach.id
          flash.notice = "ログインしました。"
          redirect_to :external_coach_root
        end

    else
      render action: "new"
    end
  end

  def destroy
    external_coach = ExternalCoach.find(params[:id])
    external_coach.destroy!
    flash.notice = "職員アカウントを削除しました。"
    redirect_to :external_coach_root
  end

  private def new_form_params
    params.require(:external_coach).permit(:email, :password)
  end

  private def external_coach_params
    params.require(:external_coach).permit(
        :email,
        :password,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :club_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end

end

app/views/external_coach/accounts/edit.html.erb
<% @page_title = "会員情報の編集" %>

<h1><%= @page_title %></h1>

<div class="toolbar"><%= link_to "会員の詳細に戻る", :external_coach_account %></div>

<%= render "shared/errors", obj: @external_coach %>

<%= form_with model: @external_coach, url: external_coach_account_path(@external_coach) do |form| %>
    <table class="attr">
        <tr>
            <th><%= form.label :family_name %></th>
            <td><%= form.text_field :family_name %></td>
            <td><%= form.text_field :given_name %></td>
        </tr>
        <tr>
            <th><%= form.label :family_name_kana %></th>
            <td><%= form.text_field :family_name_kana %></td>
            <td><%= form.text_field :given_name_kana %></td>
        </tr>
        <tr>
            <th><%= ExternalCoach.human_attribute_name(:sex) %></th>
            <td>
            <%= form.radio_button :sex, 1 %>
            <%= form.label :sex_1 %>
            <%= form.radio_button :sex, 2 %>
            <%= form.label :sex_2 %>
            </td>
        </tr>
        <tr>
            <th><%= form.label :birthday, for: "external_coach_birthday_1i" %></th>
            <td><%= form.date_select :birthday,
                    start_year: 1940, end_year: Time.current.year,
                    use_month_numbers: true %></td>
        </tr>
        <tr>
            <th><%= form.label :email %></th>
            <td><%= form.text_field :email %></td>
        </tr>
        <tr>
            <th><%= form.label :sport_id %></th>
            <td><%= form.text_field :sport_id, size: 8 %></td>
        </tr>
        <% if @external_coach.new_record? %>
            <tr>
            <th><%= ExternalCoach.human_attribute_name(:password) %></th>
            <td><%= form.text_field :password %></td>
            </tr>
        <% end %>
        <% if controller.kind_of?(ExternalCoach::UsersController) %>
            <tr>
            <th><%= ExternalCoach.human_attribute_name(:external_coach) %></th>
            <td>
                <%= form.check_box :external_coach %>
                <%= form.label :external_coach %>
            </td>
            </tr>
        <% end %>
        <tr>
            <td><%= form.submit "更新" %></td>
        </tr>
    </table>    
  <div></div>
<% end %>

app/views/external_coach/accounts/show.html.erb
<div class="py-12">
  <div class="flex justify-around">
    <div class="w-5/6 mx-8 w-1/6 lg:px-4">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">
          <ul class="toolbar">
            <tr><%= link_to "公開プロフィール", :external_coach_profile %></tr>
            <tr><%= link_to "アカウント情報の編集", :external_coach_account %></tr>
          </ul>
        </div>
      </div>
    </div>

    <div class="ml-32 w-5/6 mx-16 w-5/6">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">
            <% @page_title = "マイアカウント" %>
            <% @current_external_coach %>

            <h1><%= @page_title %></h1>

            <div class="toolbar"><%= link_to "編集", :edit_external_coach_account %></div>

            <table class="attr">
                <tr>
                    <th>氏名</th>
                    <td><%= @external_coach.family_name %></td>
                    <td><%= @external_coach.given_name %></td>
                </tr>
                <tr>
                    <th>フリガナ</th>
                    <td><%= @external_coach.family_name_kana %></td>
                    <td><%= @external_coach.given_name_kana %></td>
                </tr>
                <tr>
                    <th>性別</th>
                    <td><%= @external_coach.sex == 1 ? '男' : '女' %></td>
                </tr>
                <tr>
                    <th>誕生日</th>
                    <td><%= @external_coach.birthday.strftime("%Y年%m月%d日") %></td>
                </tr>
                <tr>
                    <th>メールアドレス</th>
                    <td><%= @external_coach.email %></td>
                </tr>
                <tr>
                    <th>場所</th>
                    <td><%= @external_coach.area_id %></td>
                </tr>
                <tr>
                    <th>スポーツ名</th>
                    <td><%= @external_coach.sport_id %></td>
                </tr>
            </table>
        </div>
      </div>
    </div>
  </div>
</div>