config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'auth/registrations'
  }
  namespace :external_coach do
    root "users#index"
    get "login" => "sessions#new", as: :login
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy"


    # profileルーティング
    resource :profile

    # userルーティング
    resources :users

    # 記事
    resources :articles

    # accountルーティング
    resource :account, only: [:show, :edit, :update]

    # passwordルーティング
    resource :password, only: [:show, :edit, :update]
  end

  namespace :club_advisor do
    get "login" => "sessions#new", as: :login
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy"

    root "articles#index"

    # 記事
    resources :external_coaches 
    resources :articles

    # accountルーティング
    resource :account, only: [:show, :edit, :update]

    # userルーティング
    resources :users
    
    # profileルーティング
    resource :profile

    # passwordルーティング
    resource :password, only: [:show, :edit, :update]
  end
end

app/models/club_advisor.rb
class ClubAdvisor < ApplicationRecord
  has_one :ca_article, dependent: :destroy 

  # クラブアドバイザーがフォローしている外部コーチの関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following

  # クラブアドバイザーをフォローしている外部コーチの関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

  # current_passwordの書き込み・読み取りを可能にする
  attr_accessor :current_password

  # バリデーションの設定
  HUMAN_NAME_REGEXP = /\A[\p{han}\p{hiragana}\p{katakana}\u{30fc}A-Za-z]+\z/
  KATAKANA_REGEXP = /\A[\p{katakana}\u{30fc}]+\z/

  validates :email, presence: true, "valid_email_2/email": true,
    uniqueness: { case_sensitive: false }
  validates :family_name, :given_name, presence: true,
    format: { with: HUMAN_NAME_REGEXP, allow_blank: true }
  validates :family_name_kana, :given_name_kana, presence: true,
    format: { with: KATAKANA_REGEXP, allow_blank: true }
  validates :start_date, presence: true, date: {
    after_or_equal_to: Date.new(2000, 1, 1),
    before: -> (obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
  validates :end_date, date: {
    after: :start_date,
    before: -> (obj) { 1.year.from_now.to_date },
    allow_blank: true
  }

  # パスワード変更時のバリデーション, このバリデーションは、「password」という属性（カラム）に対して、存在性（presence）のバリデーションを行うことを意味しています。「if: :current_password」というオプションは、「current_password」というメソッドが「true」を返す場合のみバリデーションが実行されます。
  validates :password, presence: {if: :current_password}

  validate :above_18_years_old

  def above_18_years_old
    if birthday.present? && birthday >= 18.years.ago.to_date
      errors.add(:birthday, "must be above 18 years old")
    end
  end

  validates :sex, presence: true

  def is_followed_by?(external_coach)
    active_relationships.find_by(following_id: external_coach.id).present?
  end
end

app/controllers/club_advisor/accounts_controller.rb
class ClubAdvisor::AccountsController < ClubAdvisor::Base
  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @club_advisor = current_club_advisor
  end

  def edit
    @club_advisor = current_club_advisor
  end
  
  def update
    @club_advisor = current_club_advisor
    @club_advisor.assign_attributes(ca_account_params)
    if @club_advisor.save
      redirect_to :club_advisor_account, notice: "アカウント情報を更新しました。"
    else
      render "edit"
    end
  end

  private def ca_account_params
    params.require(:club_advisor).permit(
        :email,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :school_id,
        :club_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end

end

app/controllers/club_advisor/articles_controller.rb
class ClubAdvisor::ArticlesController < ClubAdvisor::Base
  
  # 外部コーチ:記事一覧
  def index
    @articles = EcArticle.common
    .visible.order(released_at: :desc)
    .page(params[:page]).per(5)
    render json: @articles
  end

  # 外部コーチ:記事詳細
  def show
    @article = EcArticle.find(params[:id])
  end
end

app/controllers/club_advisor/base.rb
class ClubAdvisor::Base < ApplicationController
  private def current_club_advisor
    if session[:club_advisor_id]
      @current_club_advisor ||=
        ClubAdvisor.find_by(id: session[:club_advisor_id])
    end
  end
  
  # before_actionコールバックとして使うためlogin_requiredを作成
  private def login_required
    raise LoginRequired unless current_club_advisor
  end  
  helper_method :current_club_advisor
end

app/controllers/club_advisor/passwords_controller.rb
class ClubAdvisor::PasswordsController < ClubAdvisor::Base
  before_action :login_required

  def show
    redirect_to :edit_club_advisor_password
  end

  def edit
    @change_password_form =
      ClubAdvisor::ChangePasswordForm.new(object: current_club_advisor)
  end

  def update
    @change_password_form = ClubAdvisor::ChangePasswordForm.new(club_advisor_params)
    @change_password_form.object = current_club_advisor
    if @change_password_form.save
      flash.notice = "パスワードを変更しました。"
      redirect_to :club_advisor_account
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "edit"
    end
  end

  private def club_advisor_params
    params.require(:club_advisor_change_password_form).permit(
      :current_password, :new_password, :new_password_confirmation
    )
  end
end

app/controllers/club_advisor/profiles_controller.rb
class ClubAdvisor::ProfilesController < ClubAdvisor::Base
  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required
  
  def show
    @club_advisor = current_club_advisor
    @article = @club_advisor.ca_article
  end

  # クラブアドバイザー:編集フォーム
  def edit
    @club_advisor = current_club_advisor
    @article = @club_advisor.ca_article
  end

  # クラブアドバイザー:新規登録フォーム
  def new
    if CaArticle.exists?(club_advisor_id: current_club_advisor)
      redirect_to :club_advisor_articles
    else
      @article = CaArticle.new
    end
  end


  # クラブアドバイザー:新規作成
  def create
    @article = CaArticle.new(ca_article_params)
    @article.author = current_club_advisor
    if @article.save
      redirect_to :club_advisor_articles, notice: "ニュース記事を登録しました。"
    else
      render "new"
    end
  end

  # クラブアドバイザー:更新
  def update
    @club_advisor = current_club_advisor
    @article = @club_advisor.ca_article
    @article.assign_attributes(ca_article_params)
    if @article.save
      redirect_to club_advisor_profile_path(@article), notice: "ニュース記事を更新しました。"
    else
      render "edit"
    end
  end

  # クラブアドバイザー:削除
  def destroy
    @article = CaArticle.find(params[:id])
    @article.destroy
    redirect_to :club_advisor_articles
  end

  private def ca_article_params
    params.require(:ca_article).permit(
        :title,
        :body_1,
        :body_2,
        :body_3,
        :released_at,
        :expired_at,
        :no_expiration,
        :club_advisor_only,
        :club_advisor_id,
        :status
    )
  end

  private def redirect_if_data_present
    if current_club_advisor.ca_article.present?
        redirect_to :club_advisor_articles
    end
  end
end

app/controllers/club_advisor/relationships_controller.rb
class ClubAdvisor::RelationshipsController < ClubAdvisor::Base
  before_action :login_required
  def create
    following = current_club_advisor.active_relationships.build(following_id: params[:external_coach_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_club_advisor.active_relationships.find_by(following_id: params[:external_coach_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/controllers/club_advisor/sessions_controller.rb
class ClubAdvisor::SessionsController < ClubAdvisor::Base
  def new
    if current_club_advisor
      redirect_to :club_advisor_root
    else
      @form = ClubAdvisor::LoginForm.new
      render action: "new"
    end
  end

  def create
    @form = ClubAdvisor::LoginForm.new(login_form_params)
    if @form.email.present?
      club_advisor =
        ClubAdvisor.find_by("LOWER(email) = ?", @form.email.downcase)
    end
    if ClubAdvisor::Authenticator.new(club_advisor).authenticate(@form.password)
      if club_advisor.suspended?
        flash.now.alert = "アカウントが停止されています。"
        render action: "new"
      else
        session[:club_advisor_id] = club_advisor.id
        flash.notice = "ログインしました。"
        redirect_to :club_advisor_users
      end
    else
      flash.now.alert = "メールアドレスまたはパスワードが正しくありません。"
      render action: "new"
    end
  end

  private def login_form_params
    params.require(:club_advisor_login_form).permit(:email, :password)
  end

  def destroy
    session.delete(:club_advisor_id)
    flash.notice = "ログアウトしました。"
    redirect_to :club_advisor_root
  end
end

app/controllers/club_advisor/users_controller.rb
class ClubAdvisor::UsersController < ClubAdvisor::Base
  def index
    @club_advisor = ClubAdvisor.order(:family_name_kana, :given_name_kana)
    # ページネーション
    .page(params[:page]).per(15)
    render json: @club_advisor
  end

  def show
    @club_advisor = ClubAdvisor.find(params[:id])
    redirect_to [ :edit, :admin, club_advisor ]
  end

  def new
    if current_club_advisor
      redirect_to :club_advisor_root
    else
      @club_advisor = ClubAdvisor.new
      render action: "new"
    end
  end

  def edit
    @club_advisor = ClubAdvisor.find(params[:id])
  end

  def update
    @club_advisor = ClubAdvisor.find(params[:id])
    @club_advisor.assign_attributes(params[:club_advisor])
    if @club_advisor.save
      flash.notice = "職員アカウントを更新しました。"
      redirect_to :club_advisor_users
    else
      render action: "edit"
    end
  end
 
  def create
    @club_advisor = ClubAdvisor.new(club_advisor_params)
    if @club_advisor.save
      flash.notice = "職員アカウントを新規登録しました。"
      render json: @club_advisor, status: :created
      #redirect_to :club_advisor_users



    else
      Rails.logger.debug @club_advisor.errors.full_messages # 追加
      render action: "new"
    end
  end

  def destroy
    club_advisor = ClubAdvisor.find(params[:id])
    club_advisor.destroy!
    flash.notice = "職員アカウントを削除しました。"
    redirect_to :club_advisor_root
  end

  private def new_form_params
    params.require(:club_advisor).permit(:email, :password)
  end

  private def club_advisor_params
    params.require(:club_advisor).permit(
        :email,
        :password,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :school_id,
        :club_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end
end

app/controllers/external_coach/accounts_controller.rb
class ExternalCoach::AccountsController < ExternalCoach::Base

  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @external_coach = current_external_coach
  end

  def edit
    @external_coach = current_external_coach
  end
  
  def update
    @external_coach = current_external_coach
    @external_coach.assign_attributes(ec_account_params)
    if @external_coach.save
      redirect_to :external_coach_account, notice: "アカウント情報を更新しました。"
    else
      render "edit"
    end
  end

  private def ec_account_params
    params.require(:external_coach).permit(
        :email,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end
end

app/views/club_advisor/accounts/edit.html.erb
<% @page_title = "会員情報の編集" %>

<h1><%= @page_title %></h1>

<div class="toolbar"><%= link_to "会員の詳細に戻る", :club_advisor_account %></div>

<%= render "shared/errors", obj: @club_advisor %>

<%= form_with model: @club_advisor, url: club_advisor_account_path(@club_advisor) do |form| %>
    <table class="attr">
        <tr>
            <th><%= form.label :family_name %></th>
            <td><%= form.text_field :family_name %></td>
            <td><%= form.text_field :given_name %></td>
        </tr>
        <tr>
            <th><%= form.label :family_name_kana %></th>
            <td><%= form.text_field :family_name_kana %></td>
            <td><%= form.text_field :given_name_kana %></td>
        </tr>
        <tr>
            <th><%= ClubAdvisor.human_attribute_name(:sex) %></th>
            <td>
            <%= form.radio_button :sex, 1 %>
            <%= form.label :sex_1 %>
            <%= form.radio_button :sex, 2 %>
            <%= form.label :sex_2 %>
            </td>
        </tr>
        <tr>
            <th><%= form.label :birthday, for: "club_advisor_birthday_1i" %></th>
            <td><%= form.date_select :birthday,
                    start_year: 1940, end_year: Time.current.year,
                    use_month_numbers: true %></td>
        </tr>
        <tr>
            <th><%= form.label :email %></th>
            <td><%= form.text_field :email %></td>
        </tr>
        <tr>
            <th><%= form.label :sport_id %></th>
            <td><%= form.text_field :sport_id, size: 8 %></td>
        </tr>
        <% if @club_advisor.new_record? %>
            <tr>
            <th><%= ClubAdvisor.human_attribute_name(:password) %></th>
            <td><%= form.text_field :password %></td>
            </tr>
        <% end %>
        <% if controller.kind_of?(ClubAdvisor::UsersController) %>
            <tr>
            <th><%= ClubAdvisor.human_attribute_name(:club_advisor) %></th>
            <td>
                <%= form.check_box :club_advisor %>
                <%= form.label :club_advisor %>
            </td>
            </tr>
        <% end %>
        <tr>
            <td><%= form.submit "更新" %></td>
        </tr>
    </table>    
  <div></div>
<% end %>

app/views/club_advisor/accounts/show.html.erb
<div class="py-12">
  <div class="flex justify-around">
    <div class="w-5/6 mx-8 w-1/6 lg:px-4">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">
          <table>
          <tr class="toolbar">
              <td><%= link_to "公開プロフィール", :club_advisor_profile %></td>
          </tr>
              <td><%= link_to "アカウント情報の編集", :club_advisor_account %></td>
          </table>
        </div>
      </div>
    </div>

    <div class="ml-32 w-5/6 mx-16 w-5/6">
      <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6 bg-white border-b border-gray-200">
            <% @page_title = "マイアカウント" %>
            <% @current_club_advisor %>

            <h1><%= @page_title %></h1>

            <div class="toolbar"><%= link_to "編集", :edit_club_advisor_account %></div>

            <table class="attr">
                <tr>
                    <th>氏名</th>
                    <td><%= @club_advisor.family_name %></td>
                    <td><%= @club_advisor.given_name %></td>
                </tr>
                <tr>
                    <th>フリガナ</th>
                    <td><%= @club_advisor.family_name_kana %></td>
                    <td><%= @club_advisor.given_name_kana %></td>
                </tr>
                <tr>
                    <th>性別</th>
                    <td><%= @club_advisor.sex == 1 ? '男' : '女' %></td>
                </tr>
                <tr>
                    <th>誕生日</th>
                    <td><%= @club_advisor.birthday.strftime("%Y年%m月%d日") %></td>
                </tr>
                <tr>
                    <th>メールアドレス</th>
                    <td><%= @club_advisor.email %></td>
                </tr>
                <tr>
                    <th>場所</th>
                    <td><%= @club_advisor.area_id %></td>
                </tr>
                <tr>
                    <th>スポーツ名</th>
                    <td><%= @club_advisor.sport_id %></td>
                </tr>
                <tr>
                    <th>管理者</th>
                    <td><%= @club_advisor.suspended? ? "○" : "－" %></td>
                </tr>
            </table>

        </div>
      </div>
    </div>
  </div>
</div>