config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth', controllers: {
    registrations: 'auth/registrations'
  }
  namespace :external_coach do
    root "users#index"
    get "login" => "sessions#new", as: :login
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy"


    # profileルーティング
    resource :profile

    # userルーティング
    resources :users

    # 記事
    resources :articles

    # accountルーティング
    resource :account, only: [:show, :edit, :update]

    # passwordルーティング
    resource :password, only: [:show, :edit, :update]
  end

  namespace :club_advisor do
    get "login" => "sessions#new", as: :login
    post "session" => "sessions#create", as: :session
    delete "session" => "sessions#destroy"

    root "articles#index"

    # 記事
    resources :external_coaches 
    resources :articles

    # accountルーティング
    resource :account, only: [:show, :edit, :update]

    # userルーティング
    resources :users
    
    # profileルーティング
    resource :profile

    # passwordルーティング
    resource :password, only: [:show, :edit, :update]
  end
end

app/models/external_coach.rb
class ExternalCoach < ApplicationRecord
  has_one :ec_article, dependent: :destroy 

  # 外部コーチがフォローしているクラブアドバイザーの関連付け
  has_many :active_relationships, class_name: "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :follower

  # 外部コーチをフォローしているクラブアドバイザーの関連付け
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    elsif raw_password.nil?
      self.hashed_password = nil
    end
  end

  # current_passwordの書き込み・読み取りを可能にする
  attr_accessor :current_password

  # バリデーションの設定
  HUMAN_NAME_REGEXP = /\A[\p{han}\p{hiragana}\p{katakana}\u{30fc}A-Za-z]+\z/
  KATAKANA_REGEXP = /\A[\p{katakana}\u{30fc}]+\z/

  validates :email, presence: true, "valid_email_2/email": true,
    uniqueness: { case_sensitive: false }
  validates :family_name, :given_name, presence: true,
    format: { with: HUMAN_NAME_REGEXP, allow_blank: true }
  validates :family_name_kana, :given_name_kana, presence: true,
    format: { with: KATAKANA_REGEXP, allow_blank: true }
  validates :start_date, presence: true, date: {
    after_or_equal_to: Date.new(2000, 1, 1),
    before: -> (obj) { 1.year.from_now.to_date },
    allow_blank: true
  }
  validates :end_date, date: {
    after: :start_date,
    before: -> (obj) { 1.year.from_now.to_date },
    allow_blank: true
  }

  # パスワード変更時のバリデーション, このバリデーションは、「password」という属性（カラム）に対して、存在性（presence）のバリデーションを行うことを意味しています。「if: :current_password」というオプションは、「current_password」というメソッドが「true」を返す場合のみバリデーションが実行されます。
  validates :password, presence: {if: :current_password}

  validate :above_18_years_old

  def above_18_years_old
    if birthday.present? && birthday >= 18.years.ago.to_date
      errors.add(:birthday, "must be above 18 years old")
    end
  end

  validates :sex, presence: true

  def is_followed_by?(club_advisor)
    active_relationships.find_by(follower_id: club_advisor.id).present?
  end
end

app/controllers/club_advisor/articles_controller.rb
class ClubAdvisor::ArticlesController < ClubAdvisor::Base
  
  # 外部コーチ:記事一覧
  def index
    @articles = EcArticle.common
    .visible.order(released_at: :desc)
    .page(params[:page]).per(5)
    render json: @articles
  end

  # 外部コーチ:記事詳細
  def show
    @article = EcArticle.find(params[:id])
  end
end

app/controllers/external_coach/accounts_controller.rb
class ExternalCoach::AccountsController < ExternalCoach::Base

  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @external_coach = current_external_coach
  end

  def edit
    @external_coach = current_external_coach
  end
  
  def update
    @external_coach = current_external_coach
    @external_coach.assign_attributes(ec_account_params)
    if @external_coach.save
      redirect_to :external_coach_account, notice: "アカウント情報を更新しました。"
    else
      render "edit"
    end
  end

  private def ec_account_params
    params.require(:external_coach).permit(
        :email,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end
end

app/controllers/external_coach/articles_controller.rb
class ExternalCoach::ArticlesController < ExternalCoach::Base
  
  #クラブアドバイザー:記事一覧
  def index
      @articles = CaArticle.common
      .visible.order(released_at: :desc)
      .page(params[:page]).per(5)
      render json: @articles
  end

  # クラブアドバイザー:記事詳細
  def show
    @article = CaArticle.find(params[:id])
  end
end

app/controllers/external_coach/base.rb
class ExternalCoach::Base < ApplicationController
  private def current_external_coach
    if session[:external_coach_id]
      @current_external_coach ||=
        ExternalCoach.find_by(id: session[:external_coach_id])
    end
  end
  
  # before_actionコールバックとして使うためlogin_requiredを作成
  private def login_required
    raise LoginRequired unless current_external_coach
  end
  helper_method :current_external_coach
end

app/controllers/external_coach/passwords_controller.rb
class ExternalCoach::PasswordsController < ExternalCoach::Base
  before_action :login_required

  def show
    redirect_to :edit_external_coach_password
  end

  def edit
    @change_password_form =
      ExternalCoach::ChangePasswordForm.new(object: current_external_coach)
  end

  def update
    @change_password_form = ExternalCoach::ChangePasswordForm.new(external_coach_params)
    @change_password_form.object = current_external_coach
    if @change_password_form.save
      flash.notice = "パスワードを変更しました。"
      redirect_to :external_coach_account
    else
      flash.now.alert = "入力に誤りがあります。"
      render action: "edit"
    end
  end

  private def external_coach_params
    params.require(:external_coach_change_password_form).permit(
      :current_password, :new_password, :new_password_confirmation
    )
  end

end

app/controllers/external_coach/profiles_controller.rb
class ExternalCoach::ProfilesController < ExternalCoach::Base
  
  # ログイン前にアクセスするとエラーページに遷移
  before_action :login_required

  def show
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
  end

  # 外部コーチ:編集フォーム
  def edit
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
  end

  # 外部コーチ:新規登録フォーム
  def new
    if EcArticle.exists?(external_coach_id: current_external_coach)
      redirect_to :external_coach_articles
    else
      @article = EcArticle.new
    end
  end

  # 外部コーチ:新規作成
  def create
    @article = EcArticle.new(ec_article_params)
    @article.author = current_external_coach
    if @article.save
      redirect_to :external_coach_profile, notice: "ニュース記事を登録しました。"
    else
      render "new"
    end
  end

  # 外部コーチ:更新
  def update
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
    @article.assign_attributes(ec_article_params)
    if @article.save
      redirect_to external_coach_profile_path(@article), notice: "ニュース記事を更新しました。"
    else
      render "edit"
    end
  end

  # 外部コーチ:削除
  def destroy
    @external_coach = current_external_coach
    @article = @external_coach.ec_article
    @article.destroy
    redirect_to :external_coach_profile
  end

  private def ec_article_params
    params.require(:ec_article).permit(
        :title,
        :body_1,
        :body_2,
        :body_3,
        :released_at,
        :expired_at,
        :no_expiration,
        :external_coach_only,
        :external_coach_id,
        :status
    )
  end
  
  private def redirect_if_data_present
    if current_external_coach.ec_article.present?
        redirect_to :external_coach_articles
    end
  end
end

app/controllers/external_coach/relationships_controller.rb
class ExternalCoach::RelationshipsController < ExternalCoach::Base
  before_action :login_required
  def create
    following = current_external_coach.active_relationships.build(follower_id: params[:club_advisor_id])
    following.save
    redirect_to request.referrer || root_path
  end

  def destroy
    following = current_external_coach.active_relationships.find_by(follower_id: params[:club_advisor_id])
    following.destroy
    redirect_to request.referrer || root_path
  end
end

app/controllers/external_coach/sessions_controller.rb
class ExternalCoach::SessionsController < ExternalCoach::Base
  def new
    if current_external_coach
      redirect_to :external_coach_root
    else
      @form = ExternalCoach::LoginForm.new
      render action: "new"
    end
  end

  def create
    @form = ExternalCoach::LoginForm.new(login_form_params)
    if @form.email.present?
      external_coach =
        ExternalCoach.find_by("LOWER(email) = ?", @form.email.downcase)
    end
    if ExternalCoach::Authenticator.new(external_coach).authenticate(@form.password)
      if external_coach.suspended?
        flash.now.alert = "アカウントが停止されています。"
        render action: "new"
      else
        session[:external_coach_id] = external_coach.id
        flash.notice = "ログインしました。"
        redirect_to :external_coach_users
      end
    else
      flash.now.alert = "メールアドレスまたはパスワードが正しくありません。"
      render action: "new"
    end
  end

  private def login_form_params
    params.require(:external_coach_login_form).permit(:email, :password)
  end

  def destroy
    session.delete(:external_coach_id)
    flash.notice = "ログアウトしました。"
    redirect_to :external_coach_root
  end
end

app/controllers/external_coach/users_controller.rb
class ExternalCoach::UsersController < ExternalCoach::Base
  def index
    @external_coach = ExternalCoach.order(:family_name_kana, :given_name_kana)
    # ページネーション
    .page(params[:page]).per(15)
    render json: @external_coach
  end

  def show
    @external_coach = ExternalCoach.find(params[:id])
    redirect_to [ :edit, :admin, external_coach ]
  end

  def new
    if current_external_coach
      redirect_to :external_coach_root
    else
      @external_coach = ExternalCoach.new
      render action: "new"
    end
  end

  def edit
    @external_coach = ExternalCoach.find(params[:id])
  end

  def update
    @external_coach = ExternalCoach.find(params[:id])
    @external_coach.assign_attributes(params[:external_coach])
    if @external_coach.save
      flash.notice = "職員アカウントを更新しました。"
      redirect_to :external_coach_users
    else
      render action: "edit"
    end
  end
 
  def create
    @external_coach = ExternalCoach.new(external_coach_params)
    if @external_coach.save
      flash.notice = "職員アカウントを新規登録しました。"
      #redirect_to :external_coach_root

      @form = ExternalCoach::LoginForm.new(new_form_params)
      if @form.email.present?
        external_coach =
          ExternalCoach.find_by("LOWER(email) = ?", @form.email.downcase)
      end
        if ExternalCoach::Authenticator.new(external_coach).authenticate(@form.password)
          session[:external_coach_id] = external_coach.id
          flash.notice = "ログインしました。"
          redirect_to :external_coach_root
        end

    else
      render action: "new"
    end
  end

  def destroy
    external_coach = ExternalCoach.find(params[:id])
    external_coach.destroy!
    flash.notice = "職員アカウントを削除しました。"
    redirect_to :external_coach_root
  end

  private def new_form_params
    params.require(:external_coach).permit(:email, :password)
  end

  private def external_coach_params
    params.require(:external_coach).permit(
        :email,
        :password,
        :family_name,
        :given_name,
        :family_name_kana,
        :given_name_kana,
        :career,
        :start_date,
        :end_date,
        :suspended,
        :sport_id,
        :area_id,
        :club_id,
        :created_at,
        :updated_at,
        :birthday,
        :sex
    )
  end

end

app/views/external_coach/articles/_footer.html.erb
<ul class="article-footer">
  <% if current_external_coach %>
    <li><%= EcArticle.status_text(article.status) %></li>
    <% if current_external_coach == article.author %>
      <%= menu_link_to "画像", [article, :images] %>
    <% end %>
  <% end %>
</ul>

app/views/external_coach/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
<table class="attr">
  <tr>
    <th><%= form.label :title %></th>
    <td><%= form.text_field :title, size: 20 %></td>
  </tr>
  <tr>
    <th><%= form.label :body_1 %></th>
    <td><%= form.text_area :body_1, rows: 10, cols: 45 %></td>
  </tr>
  <tr>
    <th><%= form.label :body_2 %></th>
    <td><%= form.text_area :body_2, rows: 10, cols: 45 %></td>
  </tr>
  <tr>
    <th><%= form.label :body_3 %></th>
    <td><%= form.text_area :body_3, rows: 10, cols: 45 %></td>
  </tr>
  <tr>
    <th><%= form.label :released_at, for: "article_released_at_1i" %></th>
    <td><%= form.datetime_select :released_at,
              start_year: 2000, end_year: Time.current.year + 1,
              use_month_numbers: true %></td>
  </tr>
  <tr>
    <th><%= form.label :expired_at, for: "article_expired_at_1i" %></th>
    <td>
      <div>
        <%= form.check_box :no_expiration %>
        <%= form.label :no_expiration %>
      </div>
      <div>
        <%= form.datetime_select :expired_at,
          start_year: 2000, end_year: Time.current.year + 1,
          use_month_numbers: true %>
      </div>
    </td>
  </tr>
  <tr>
    <th><%= EcArticle.human_attribute_name(:external_coach_only) %></th>
    <td>
      <%= form.check_box :external_coach_only %>
      <%= form.label :external_coach_only %>
    </td>
  </tr>
</table>

app/views/external_coach/articles/index.html.erb
<% @page_title = "クラブアドバイザー記事一覧" %>
<h1><%= @page_title %></h1>

<% if @articles.present? %>
  <table class="list">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>日時</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <!-- 掲載期間内であれば表示する -->
      <% article = CaArticle.visible.order(released_at: :desc) %>
      <% article.each do |article| %>
      <!-- truncateは引数に指定された文字列がある長さを超えていれば切って、省略記号（...）を加えて返します。-->
      <tr>
        <td><%= link_to article.title, external_coach_article_path(article) %></td>
        <td>
          <%= truncate article.body_1, length: 80 %>
          <%= link_to "もっと読む", external_coach_article_path(article) %>
        </td>
        <td><%= article.released_at.strftime("%Y/%m/%d %H:%M") %></td>
      </tr>
      <% end %>
      <!-- end -->
    </tbody>
  </table>
<% else %>
  <p>記事がまだありません。</p>
<% end %>
<%= paginate @articles %>

app/views/external_coach/articles/new.html.erb
<% @page_title = "ニュース記事の新規登録" %>
<h1><%= @page_title %></h1>

<%= form_with model: @article, url: :external_coach_articles do |form| %>
  <%= render "form", form: form %>
  <div><%= form.submit "作成する" %></div>
<% end %>

app/views/external_coach/articles/show.html.erb
<% @page_title = @article.title %>
<h1><%= @article.title %></h1>

<% if current_external_coach %>
  <div class="toolbar">
    <%= link_to "編集", edit_external_coach_article_path(@article) %>
  </div>
<% end %>

<table class="attr">
  <tr>
    <th width="100">タイトル</th>
    <td><%= @article.title %></td>
  </tr>
  <tr>
    <th>本文</th>
    <td><%= simple_format(@article.body_1) %></td>
  </tr>
  <tr>
    <th>本文</th>
    <td><%= simple_format(@article.body_2) %></td>
  </tr>
  <tr>
    <th>本文</th>
    <td><%= simple_format(@article.body_3) %></td>
  </tr>
  <tr>
    <th>掲載開始日時</th>
    <td><%= @article.released_at.strftime("%Y/%m/%d %H:%M") %></td>
  </tr>
  <tr>
    <th>掲載終了日時</th>
    <td><%= @article.expired_at.try(:strftime, "%Y/%m/%d %H:%M") %></td>
  </tr>
</table>

<% if @club_advisor.is_followed_by?(current_external_coach) %>
  <%=link_to external_coach_relationships_path(club_advisor_id: @club_advisor.id), method: :delete do %>
    <button type="button" class="btn btn btn-danger">フォロー解除</button>
  <% end %>
<% else %>
  <%=link_to external_coach_relationships_path(club_advisor_id: @club_advisor.id), method: :post do %>
    <button type="button" class="btn btn btn-primary">フォロー</button>
  <% end %>
<% end %>
<%= link_to "戻る", :external_coach_articles %>